In [4]:
import numpy as np
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [26]:
# Load training data
tr_jinsAcc = np.load("/content/drive/MyDrive/bbh/training/trainJinsAccelerometer.npy")
tr_jinsGyr = np.load("/content/drive/MyDrive/bbh/training/trainJinsGyroscope.npy")
tr_labels = np.load("/content/drive/MyDrive/bbh/training/trainLabels.npy")

# Load testing data
ts_jinsAcc = np.load("/content/drive/MyDrive/bbh/testing/testJinsAccelerometer.npy")
ts_jinsGyr = np.load("/content/drive/MyDrive/bbh/testing/testJinsGyroscope.npy")
ts_labels = np.load("/content/drive/MyDrive/bbh/testing/testLabels.npy")

print("Training Accelerometer shape:", tr_jinsAcc.shape)
print("Training Gyroscope shape:", tr_jinsGyr.shape)
print("Training Labels shape:", tr_labels.shape)

print("Testing Accelerometer shape:", ts_jinsAcc.shape)
print("Testing Gyroscope shape:", ts_jinsGyr.shape)
print("Testing Labels shape:", ts_labels.shape)

\Training Accelerometer shape: (2284, 80, 3)
Training Gyroscope shape: (2284, 80, 3)
Training Labels shape: (2284,)
\Testing Accelerometer shape: (2288, 80, 3)
Testing Gyroscope shape: (2288, 80, 3)
Testing Labels shape: (2288,)


In [30]:
# Define activity labels
OPEN_DOOR = 20
RUB_HANDS = 36

# Training data filtering
tr_labels_OPEN_DOOR_idx = tr_labels == OPEN_DOOR
tr_labels_RUB_HANDS_idx = tr_labels == RUB_HANDS

tr_jinsAcc_OPEN_DOOR = tr_jinsAcc[tr_labels_OPEN_DOOR_idx]
tr_jinsGyr_OPEN_DOOR = tr_jinsGyr[tr_labels_OPEN_DOOR_idx]

print("OPEN_DOOR Training Accelerometer shape: ",tr_jinsAcc_OPEN_DOOR.shape)

tr_jinsAcc_RUB_HANDS = tr_jinsAcc[tr_labels_RUB_HANDS_idx]
tr_jinsGyr_RUB_HANDS = tr_jinsGyr[tr_labels_RUB_HANDS_idx]

print("RUB_HANDS Training Accelerometer shape: ",tr_jinsAcc_RUB_HANDS.shape)

tr_labels_OPEN_DOOR = tr_labels[tr_labels_OPEN_DOOR_idx]
tr_labels_RUB_HANDS = tr_labels[tr_labels_RUB_HANDS_idx]

tr_jinsAcc_Two_Activities = np.concatenate((tr_jinsAcc_OPEN_DOOR, tr_jinsAcc_RUB_HANDS))
tr_jinsGyr_Two_Activities = np.concatenate((tr_jinsGyr_OPEN_DOOR, tr_jinsGyr_RUB_HANDS))
tr_labels_Two_Activities = np.concatenate((tr_labels_OPEN_DOOR, tr_labels_RUB_HANDS))

# Save filtered training data
np.save("train_JinsAccelerometer_OpenDoor_RubHands.npy", tr_jinsAcc_Two_Activities)
np.save("train_JinsGyroscope_OpenDoor_RubHands.npy", tr_jinsGyr_Two_Activities)
np.save("train_labels_OpenDoor_RubHands.npy", tr_labels_Two_Activities)

print("Combined Training Accelerometer shape:", tr_jinsAcc_Two_Activities.shape)
print("Combined Training Gyroscope shape:", tr_jinsGyr_Two_Activities.shape)
print("Combined Training Labels shape:", tr_labels_Two_Activities.shape)

OPEN_DOOR Training Accelerometer shape:  (47, 80, 3)
RUB_HANDS Training Accelerometer shape:  (40, 80, 3)
Combined Training Accelerometer shape: (87, 80, 3)
Combined Training Gyroscope shape: (87, 80, 3)
Combined Training Labels shape: (87,)


In [25]:
# Testing data filtering
ts_labels_OPEN_DOOR_idx = ts_labels == OPEN_DOOR
ts_labels_RUB_HANDS_idx = ts_labels == RUB_HANDS

ts_jinsAcc_OPEN_DOOR = ts_jinsAcc[ts_labels_OPEN_DOOR_idx]
ts_jinsGyr_OPEN_DOOR = ts_jinsGyr[ts_labels_OPEN_DOOR_idx]

ts_jinsAcc_RUB_HANDS = ts_jinsAcc[ts_labels_RUB_HANDS_idx]
ts_jinsGyr_RUB_HANDS = ts_jinsGyr[ts_labels_RUB_HANDS_idx]

ts_labels_OPEN_DOOR = ts_labels[ts_labels_OPEN_DOOR_idx]
ts_labels_RUB_HANDS = ts_labels[ts_labels_RUB_HANDS_idx]

ts_jinsAcc_Two_Activities = np.concatenate((ts_jinsAcc_OPEN_DOOR, ts_jinsAcc_RUB_HANDS))
ts_jinsGyr_Two_Activities = np.concatenate((ts_jinsGyr_OPEN_DOOR, ts_jinsGyr_RUB_HANDS))
ts_labels_Two_Activities = np.concatenate((ts_labels_OPEN_DOOR, ts_labels_RUB_HANDS))

# Save filtered testing data
np.save("test_JinsAccelerometer_OpenDoor_RubHands.npy", ts_jinsAcc_Two_Activities)
np.save("test_JinsGyroscope_OpenDoor_RubHands.npy", ts_jinsGyr_Two_Activities)
np.save("test_labels_OpenDoor_RubHands.npy", ts_labels_Two_Activities)

print("\nCombined Testing Accelerometer shape:", ts_jinsAcc_Two_Activities.shape)
print("Combined Testing Gyroscope shape:", ts_jinsGyr_Two_Activities.shape)
print("Combined Testing Labels shape:", ts_labels_Two_Activities.shape)


Combined Testing Accelerometer shape: (90, 80, 3)
Combined Testing Gyroscope shape: (90, 80, 3)
Combined Testing Labels shape: (90,)


In [27]:
# # Display samples of training data
print("\nSample of tr_jinsAcc_Two_Activities:")
print(tr_jinsAcc_Two_Activities[:5])

print("\nSample of tr_jinsGyr_Two_Activities:")
print(tr_jinsGyr_Two_Activities[:5])

print("\nSample of tr_labels_Two_Activities:")
print(tr_labels_Two_Activities[:5])

# Display samples of testing data
print("\nSample of ts_jinsAcc_Two_Activities:")
print(ts_jinsAcc_Two_Activities[:5])

print("\nSample of ts_jinsGyr_Two_Activities:")
print(ts_jinsGyr_Two_Activities[:5])

print("\nSample of ts_labels_Two_Activities:")
print(ts_labels_Two_Activities[:5])


Sample of tr_msAcc_Two_Activities:
[[[ -3.   3. -15.]
  [ -3.   3. -15.]
  [ -3.   3. -15.]
  ...
  [ -1.   3. -15.]
  [ -1.   3. -15.]
  [ -1.   3. -15.]]

 [[ -4.   5. -14.]
  [ -4.   5. -14.]
  [ -4.   5. -14.]
  ...
  [ -7.   9. -12.]
  [ -7.   9. -12.]
  [ -7.   9. -12.]]

 [[ -3.   6. -14.]
  [ -3.   6. -14.]
  [ -2.   6. -14.]
  ...
  [ -2.  -1. -25.]
  [  0.   2. -16.]
  [  0.   1. -17.]]

 [[ -4.   9. -12.]
  [ -4.   9. -13.]
  [ -4.   9. -13.]
  ...
  [ -3.  10. -12.]
  [ -3.  10. -12.]
  [ -3.  10. -12.]]

 [[ -6.   9. -11.]
  [ -6.   9. -11.]
  [ -6.   9. -12.]
  ...
  [  1.   0. -15.]
  [  2.   0. -15.]
  [  2.   0. -15.]]]

Sample of tr_msGyr_Two_Activities:
[[[-1.4400e+00  1.2340e+01  4.7410e+01]
  [-1.3600e+00  1.2410e+01  4.8960e+01]
  [-1.3500e+00  1.2180e+01  5.0520e+01]
  ...
  [-4.4300e+00  1.3890e+01  3.8150e+01]
  [-4.4700e+00  1.3890e+01  3.8110e+01]
  [-4.5500e+00  1.3910e+01  3.8080e+01]]

 [[-1.5000e+00  2.5560e+01  1.4000e-01]
  [-1.4300e+00  2.5590e+01  2.